site_name: 日本のオープンデータ 最新情報一覧・まとめ
site_description: Awesome Japan Open Data - 日本のオープンデータ、オープンデータカタログの最新情報一覧・まとめ
repo_name: japan-opendata/awesome-japan-opendata
repo_url: https://github.com/japan-opendata/awesome-japan-opendata
edit_uri: edit/master/

theme:
  name: material
  language: ja
  font:
    text: "Noto Sans JP"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
  features:
    - toc.follow
    # - toc.integrate
    - navigation.top
    # - navigation.expand
    - content.action.edit
    # - content.action.view
  icon:
    logo: material/library-shelves
    repo: fontawesome/brands/github
    # favicon: "favicon.png"

# extra_css:
#   - "extra/main.css"

plugins:
  - include-markdown
  - search

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: none
